src/objects/GVS_Settings__c.object
<CustomObject>
    <fields>
        <fullName>LastStartStep1__c</fullName>
        <label>Last Start Step 1</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>StartSynchronization__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Start Synchronization</label>
        <type>Checkbox</type>
    </fields>
    <label>GVS - Settings</label>
    <nameField>
        <label>PicklistSettings Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>GVS - Settings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/GVS_SettingsTriggerHandler.cls
public with sharing class GVS_SettingsTriggerHandler {
  public static Boolean manualSkip = false;

  public void onBeforeInsert(List<GVS_Settings__c> triggerNew, Map<Id, GVS_Settings__c> triggerNewMap){
    manageSynchronization(triggerNew);
  }
  
  public void onBeforeUpdate(List<GVS_Settings__c> triggerOld, List<GVS_Settings__c> triggerNew, Map<Id, GVS_Settings__c> triggerOldMap, Map<Id, GVS_Settings__c> triggerNewMap){
    manageSynchronization(triggerNew);
  }

  private static void manageSynchronization(List<GVS_Settings__c> triggerNew){
    List<GVS_Settings__c> settings = (List<GVS_Settings__c>) GVS_Utils.filter(triggerNew, 'StartSynchronization__c', true);
    if(settings.size() > 0){
      settings[0].LastStartStep1__c = Datetime.now();
      ID jobID = System.enqueueJob(new GVS_SyncFirstStepPicklistValue(new String[]{}, settings[0].Id));
    }
  }
}