src/objects/GVS_EnableRecordType__c.object
<CustomObject>
    <fields>
        <fullName>ExternalId__c</fullName>
        <externalId>true</externalId>
        <label>External Id</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>GVS_Picklist__c</fullName>
        <label>Picklist</label>
        <referenceTo>GVS_Picklist__c</referenceTo>
        <relationshipLabel>Picklist RecordTypes</relationshipLabel>
        <relationshipName>PicklistRecordTypes</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>PicklistName__c</fullName>
        <label>Picklist Name</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>RecordTypeName__c</fullName>
        <label>RecordType Name</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SObjectName__c</fullName>
        <label>SObject Name</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>GVS - Enable RecordType</label>
    <nameField>
        <displayFormat>GVS_RT-{0000}</displayFormat>
        <label>Enable RecordType Code</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>GVS - Enable RecordTypes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/GVS_Picklist__c.object
<CustomObject>
    <fields>
        <fullName>ExternalId__c</fullName>
        <externalId>true</externalId>
        <label>External Id</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>GlobalValueSet__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Global Value Set</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Label__c</fullName>
        <label>Label</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>GVS - Picklist</label>
    <nameField>
        <label>Picklist Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>GVS - Picklists</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/GVS_PicklistValue__c.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Default__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Default</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ExternalId__c</fullName>
        <externalId>true</externalId>
        <label>External Id</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>GVS_Picklist__c</fullName>
        <label>Picklist</label>
        <referenceTo>GVS_Picklist__c</referenceTo>
        <relationshipLabel>Picklist Values</relationshipLabel>
        <relationshipName>PicklistValues</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>GlobalValueSet__c</fullName>
        <formula>GVS_Picklist__r.GlobalValueSet__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Global Value Set</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Label__c</fullName>
        <label>Label</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Value__c</fullName>
        <label>Value</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>GVS - Picklist Value</label>
    <nameField>
        <label>Picklist Value Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>GVS - Picklist Values</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/GVS_PicklistValueDependency__c.object
<CustomObject>
    <fields>
        <fullName>ControllingFieldValue__c</fullName>
        <label>Controlling Field Value</label>
        <referenceTo>GVS_PicklistValue__c</referenceTo>
        <relationshipLabel>Dependent Picklist Values</relationshipLabel>
        <relationshipName>DepenentPicklistValues</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>DependentValue__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Dependent Value</label>
        <referenceTo>GVS_PicklistValue__c</referenceTo>
        <relationshipLabel>Controlling Picklist Values</relationshipLabel>
        <relationshipName>ControllingValues</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ExternalId__c</fullName>
        <externalId>true</externalId>
        <label>External Id</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>FieldAPIName__c</fullName>
        <inlineHelpText>API Name of the field which uses the dependent picklist</inlineHelpText>
        <label>Field API Name</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SObjectName__c</fullName>
        <label>SObject Name</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>GVS - Picklist Value Dependency</label>
    <nameField>
        <displayFormat>GVS_PVD-{000000000}</displayFormat>
        <label>Picklist Value Dependency Code</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>GVS - Picklist Value Dependencies</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/GVS_PicklistValueTranslation__c.object
<CustomObject>
    <fields>
        <fullName>ExternalId__c</fullName>
        <externalId>true</externalId>
        <label>External Id</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>GVS_PicklistValue__c</fullName>
        <label>Picklist Value</label>
        <referenceTo>GVS_PicklistValue__c</referenceTo>
        <relationshipLabel>Picklist Value Translations</relationshipLabel>
        <relationshipName>PicklistValueTranslations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>LanguageCode__c</fullName>
        <label>Language Code</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>it</fullName>
                </value>
                <value>
                    <fullName>en_US</fullName>
                </value>
                <value>
                    <fullName>fr</fullName>
                    <label>FR</label>
                </value>
                <value>
                    <fullName>de</fullName>
                </value>
                <value>
                    <fullName>es</fullName>
                </value>
                <value>
                    <fullName>zh_CN</fullName>
                </value>
                <value>
                    <fullName>ja</fullName>
                </value>
                <value>
                    <fullName>pt_BR</fullName>
                </value>
                <value>
                    <fullName>ru</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Translation__c</fullName>
        <label>Translation</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>GVS - Picklist Value Translation</label>
    <nameField>
        <displayFormat>GVS_PVT-{000000000}</displayFormat>
        <label>Picklist Value Translation Code</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>GVS - Picklist Value Translations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/GVS_Settings__c.object
<CustomObject>
    <label>GVS - Settings</label>
    <nameField>
        <label>PicklistSettings Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>GVS - Settings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/GVS_SyncFourthStepDependenciesTest.cls
@isTest
private class GVS_SyncFourthStepDependenciesTest {
  @TestSetup
  static void setupData(){
    insert new GVS_Settings__c(Name = 'Test');
    GVS_Picklist__c picklist = new GVS_Picklist__c(Name = 'MarvelGroups', Label__c = 'Marvel Groups', GlobalValueSet__c = true, ExternalId__c = 'MarvelGroups');
    insert picklist;
    GVS_Picklist__c picklistDC = new GVS_Picklist__c(Name = 'DCGroups', Label__c = 'DC Groups', GlobalValueSet__c = true, ExternalId__c = 'DCGroups');
    insert picklistDC;
    List<GVS_EnableRecordType__c> picklistRecordType = new List<GVS_EnableRecordType__c>();
    picklistRecordType.add(new GVS_EnableRecordType__c(ExternalId__c = 'Account_Hero_Group__c', SObjectName__c = 'Account', RecordTypeName__c = 'Hero', PicklistName__c = 'Group__c', GVS_Picklist__c = picklist.Id));
    picklistRecordType.add(new GVS_EnableRecordType__c(ExternalId__c = 'Account_Hero_Character__c', SObjectName__c = 'Account', RecordTypeName__c = 'Hero', PicklistName__c = 'Character__c', GVS_Picklist__c = picklist.Id));
    picklistRecordType.add(new GVS_EnableRecordType__c(ExternalId__c = 'Account_Villain_Group__c', SObjectName__c = 'Account', RecordTypeName__c = 'Villain', PicklistName__c = 'Group__c', GVS_Picklist__c = picklist.Id));
    picklistRecordType.add(new GVS_EnableRecordType__c(ExternalId__c = 'Account_Villain_Character__c', SObjectName__c = 'Account', RecordTypeName__c = 'Villain', PicklistName__c = 'Character__c', GVS_Picklist__c = picklist.Id));
    insert picklistRecordType;
    List<GVS_PicklistValue__c> groups = new List<GVS_PicklistValue__c>();
    groups.add(new GVS_PicklistValue__c(GVS_Picklist__c = picklist.Id, Name = 'Marvel Groups - Avengers', Value__c = 'Avengers', Label__c = 'Avengers', Active__c = true, Default__c = false, ExternalId__c = 'MarvelGroups_Avengers'));
    groups.add(new GVS_PicklistValue__c(GVS_Picklist__c = picklist.Id, Name = 'Marvel Groups - X-Men', Value__c = 'XMen', Label__c = 'X-Men', Active__c = true, Default__c = false, ExternalId__c = 'MarvelGroups_XMen'));
    groups.add(new GVS_PicklistValue__c(GVS_Picklist__c = picklistDC.Id, Name = 'DC Groups - Justice League of America', Value__c = 'JLA', Label__c = 'Justice League of America', Active__c = true, Default__c = false, ExternalId__c = 'DCGroups_JLA'));
    insert groups;
    List<GVS_PicklistValueTranslation__c> translations = new List<GVS_PicklistValueTranslation__c>();
    translations.add(new GVS_PicklistValueTranslation__c(GVS_PicklistValue__c = groups[0].Id, LanguageCode__c = 'it', Translation__c = 'Vendicatori', ExternalId__c = 'MarvelGroups_Avengers_it'));
    translations.add(new GVS_PicklistValueTranslation__c(GVS_PicklistValue__c = groups[1].Id, LanguageCode__c = 'it', Translation__c = 'Difensori', ExternalId__c = 'MarvelGroups_Defenders_it'));
    insert new GVS_PicklistValueDependency__c (ControllingFieldValue__c = groups[0].Id, DependentValue__c = groups[1].Id, ExternalId__c = 'AAAAAAAA', FieldAPIName__c = 'Type', SObjectName__c = 'Account');
  }

  @isTest
  private static void testPicklistValueDependencysSync(){
    Test.setMock(WebServiceMock.class, new GVS_CalloutMock());
    Test.startTest();
    System.enqueueJob(new GVS_SyncFourthStepDependencies(new String[]{}, [SELECT Id FROM GVS_Settings__c].Id));
    Test.stopTest();
  }
}