src/objects/GVS_Settings__c.object
<CustomObject>
    <fields>
        <fullName>NotifyErrorsTo__c</fullName>
        <label>Notify Errors To</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>StartSynchronization__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Start Synchronization</label>
        <type>Checkbox</type>
    </fields>
    <label>GVS - Settings</label>
    <nameField>
        <label>PicklistSettings Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>GVS - Settings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/GVS_SettingsTriggerHandlerTest.cls
@IsTest
private class GVS_SettingsTriggerHandlerTest {
  @IsTest
  private static void testSettings(){
    Test.startTest();
    GVS_Settings__c settings = new GVS_Settings__c(Name = 'TEST', StartSynchronization__c = false, NotifyErrorsTo__c = 'dlorenzi@deloitte.it');
    insert settings;
    System.assertEquals(0, [SELECT Id FROM AsyncApexJob].size());
    settings.StartSynchronization__c = true;
    update settings;
    System.assertEquals(1, [SELECT Id FROM AsyncApexJob].size());
    Test.stopTest();
  }
}